# .github/workflows/poc.yml
name: PR tests (PoC – secret exposure demo)

on:
  pull_request_target:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code (dangerous in real life)
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || echo "Skipping npm ci if no package-lock.json"

      # ✅ removed npm test to avoid ENOENT on test.js
      - name: Simulate secret exposure
        run: |
          echo "If a secret were configured, attacker PR code would access it here."
          echo "Example secret: ${{ secrets.DUMMY_SECRET || 'no secret set' }}"
